### ISSUE TITLE
Project license is missing

### ISSUE THREAD

**Issue by cvlnomen** [Bartz24/FFModdingWPF#3]
Your mods have been a great source of inspiration for my future modding projects, and I'm truly impressed with the progress you've made. I'm considering using your code and findings as a foundation for my own mods. However, there's currently no license for the project.
Could you please add an open-source license? It would protect your work and provide a clear framework for future modders like me who may want to build upon your work.

**Comment by Bartz24** [comment]
Thanks for the heads up! I didn't realize a license was missing.
Added a MIT license
